services:
  teslamate-hud:
    build: .
    #image: ghcr.io/mayrd/teslamate-hud:latest
    container_name: teslamate-hud
    restart: unless-stopped
    environment:
      - MQTT_URL
      - MQTT_TOPIC_PREFIX
      - MQTT_CAR_ID
      - PUBLIC_WS_URL

networks:
  default:
    external: true
    name: shared_network
